<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions and mass-->
  <!-- UNITS: height in meters, mass in kg, angles in rad   -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height" value="2.0" /> <!-- Base link -->
  <xacro:property name="height1" value="1.0" /> <!-- Height Link1 -->
  <xacro:property name="height2" value="1.0" /> <!-- Height Link2 -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <xacro:property name="mass1" value="1" /> <!-- Mass Link1 -->
  <xacro:property name="mass2" value="1" /> <!-- Mass Link2 -->
  <xacro:property name="init_ang1" value="${PI/2}" /> <!-- Initial angle join 1 -->
  <xacro:property name="init_ang2" value="0" /> <!-- Initial angle join 2 -->

  <!-- Import your model behavior in Gazebo -->
  <xacro:include filename="$(find bot_description)/urdf/bot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find bot_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' which is attached to a fixed reference frame located at the center of the world environment -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="baselink"/>
  </joint>

  <!-- Base Link of the robot-->
  <link name="baselink">
    <collision>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${width} ${height}"/>
      </geometry>
      <material name="BOT/orange"/>
    </visual>
    <!-- The inertia matrix values for the base do not affect the movement of the links -->
    <inertial>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia 
         ixx="1.0" ixy="0.0" ixz="0.0" 
                   iyy="1.0" iyz="0.0"
                   izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="baselink"/>
    <child link="link1"/>
    <origin xyz="0 ${width} ${height - axel_offset}" rpy="0 ${init_ang1} 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="100" velocity="1" />
    <dynamics damping="0.1"/>
  </joint>

  <!-- Middle Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="BOT/black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass1}"/>
      <inertia
         ixx="${mass1*(width*width + height1*height1)/12}"
         ixy="0.0"  
         ixz="0.0"
         iyy="${mass1*(width*width + height1*height1)/12}"
         iyz="0.0"
         izz="${mass1*(width*width + width*width)/12}"/>
    </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 ${width} ${height1 - axel_offset*2}" rpy="0 ${init_ang2} 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10" velocity="1" />
    <dynamics damping="0.1"/>
  </joint>

  <!-- Top Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="BOT/orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass2}"/>
      <inertia
         ixx="${mass2*(width*width + height2*height2)/12}"
         ixy="0.0"  
         ixz="0.0"
         iyy="${mass2*(width*width + height2*height2)/12}"
         iyz="0.0"
         izz="${mass2*(width*width + width*width)/12}"/>
    </inertial>
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
